#!/system/bin/sh
#
# Copy camera firmware to /data/cfw
#

busybox cp /system/vendor/firmware/M9MO_SFW.bin /data/cfw/
busybox cp /system/vendor/firmware/RS_M9MO.bin /data/cfw/

busybox chown system /data/cfw/*
busybox chgrp media /data/cfw/*
busybox chmod 0775 /data/cfw/*
